# Generated by Django 5.2.4 on 2025-07-17 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録した管理ユーザーID')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='購入数量')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='購入日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.product', verbose_name='商品ID')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入した一般ユーザーID')),
            ],
            options={
                'verbose_name': '購入履歴',
                'verbose_name_plural': '購入履歴',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.product', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '供給',
                'verbose_name_plural': '供給',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理ユーザーかいなか')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
    ]
